[rhel9_cluster]
node1 ansible_host=192.168.1.201 ansible_user=cesar ansible_ssh_private_key_file=./default-vm
node2 ansible_host=192.168.1.202 ansible_user=cesar ansible_ssh_private_key_file=./default-vm
node3 ansible_host=192.168.1.203 ansible_user=cesar ansible_ssh_private_key_file=./default-vm
